<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="MediatR.Contracts" Version="2.0.1" />
    <PackageReference Include="MimeKit" Version="4.11.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookingsSportsFields.Core\BookingsSportsFields.Core.csproj" />
    <ProjectReference Include="..\BookingsSportsFields.DataAccess\BookingsSportsFields.DataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Handlers\BookingHendlers\" />
  </ItemGroup>

</Project>
